name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-cam:
    name: firmware/cam (esp32)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2.3
          target: esp32
          path: firmware/cam

  build-screen:
    name: firmware/screen (esp32s3)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2.3
          target: esp32s3
          path: firmware/screen
